[project]
name = "musicdb"
version = "0.1.0"
description = "SOTA Music Similarity Search with MERT and ChromaDB"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.5",
    "click>=8.3.1",
    "fastapi>=0.135.2",
    "librosa>=0.11.0",
    "loguru>=0.7.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "python-dotenv>=1.2.2",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
    "transformers>=5.3.0",
    "uvicorn[standard]>=0.42.0",
    "yt-dlp[curl-cffi,default]>=2026.3.17",
]

[dependency-groups]
dev = [
    "ruff>=0.15.7",
]
